### ISSUE TITLE
Image links in haddock are broken

### ISSUE THREAD

**Issue by jhrcek** [diagrams/active#16]
All the image links in the haddock documentation of the active package [1] are broken.
Could you please fix the links? Thank you

[1] http://hackage.haskell.org/package/active-0.2.0.6/docs/Data-Active.html

**Comment by byorgey** [comment]
Thanks for the report!  It looks like I was hosting those images on my web space at UPenn --- I had forgotten I was doing that.  I am no longer at Penn and my account just got deleted, which is why the links all broke.  In any case we can now redo the images using `diagrams-haddock` and bundle them so they are hosted on Hackage.  I will try to do this soon.

**Comment by byorgey** [comment]
Should be fixed in `active-0.2.0.7`, though it may be a little while until the documentation gets rebuilt.

**Comment by jhrcek** [comment]
I cloned this repo and built the haddocks localy and the images are there. And they really help to understand the docs better :-) Thank you for fixing this

**Comment by byorgey** [comment]
Good, glad it helps!  Note that I am currently working on a complete rewrite of `active` which I think should make it even easier to use/understand.  But, that statement has been true for about two years now, so don't hold your breath.  In the meantime, the current `active` works just fine. =)
